[project]
name = "mvave_drumbrute_controller"
version = "0.0.1"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fire>=0.7.1",
    "python-rtmidi>=1.5.8",
    "simple-term-menu>=1.6.6",
]

[dependency-groups]
dev = [
    "ipython>=9.9.0",
]
